name: Buildifier

on:
  pull_request:
    paths:
    - '**/*.bzl'
    - '**/*.bazel'
    - 'BUILD*'
    - 'WORKSPACE*'
  push:
    paths:
    - '**/*.bzl'
    - '**/*.bazel'
    - 'BUILD*'
    - 'WORKSPACE*'
    branches:
    - master
    - release/*

jobs:

  autoformat:
    name: Auto-format and Check
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo wget -O /bin/buildifier https://github.com/bazelbuild/buildtools/releases/download/5.1.0/buildifier-linux-amd64
          sudo chmod +x /bin/buildifier

      - name: Run buildifier
        run: |
          buildifier -mode=fix $(find . -name 'BUILD*' -o -name 'WORKSPACE*' -o -name '*.bzl' -o -name '*.bazel' -type f)

      - name: suggester / buildifier
        # reviewdog/action-suggester@v1
        uses: reviewdog/action-suggester@8f83d27e749053b2029600995c115026a010408e
        with:
          github_token: ${{ secrets.GHA_COMMENT_TOKEN }}
          tool_name: buildifier
          fail_on_error: true
