name: Build & Test
on:
  pull_request:
    paths-ignore:
    # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
    - '*.md'
  push:
    paths-ignore:
    # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
    - '*.md'
    branches:
    - master
    - release/*
    - test-please/*

# cancel previous runs if new commits are pushed to the PR, but run for each commit on master
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-doc-and-unit-tests:
    name: Lint, Doc and Unit tests
    runs-on: ubuntu-20.04

    env:
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: kong

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: kong
          POSTGRES_DB: kong
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 8

    steps:
    - name: Set the path
      run: |
        echo "/usr/local/openresty/bin/" >> $GITHUB_PATH
        echo "/usr/local/openresty/nginx/sbin/" >> $GITHUB_PATH

    - name: Checkout Kong source code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}

    - name: Set .requirements into environment variables
      run: |
        grep -v '^#' .requirements >> $GITHUB_ENV
    
    - name: Setup the Kong Runtime
      run: |
        curl --fail -sSLo kong-runtime.tar.gz "https://github.com/Kong/kong-runtime/releases/download/${KONG_RUNTIME}/x86_64-linux-gnu.tar.gz"
        tar -xzvf kong-runtime.tar.gz
        sed -i 's/\/tmp\/build//' `grep -l -I -r '\/tmp\/build' usr/`
        sudo cp -R ./usr/* /usr/
        sudo mkdir -p /usr/local/lib/luarocks/rocks-5.1
        sudo chmod 777 /usr/local/lib/luarocks/rocks-5.1
        sudo chmod 777 /usr/local/share/lua/5.1
        sudo chmod 777 /usr/local/lib

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true

    - name: Install packages
      run: sudo apt update && sudo apt install libyaml-dev valgrind libprotobuf-dev libpam-dev

    - name: Install Kong dev
      run: make dev

    - name: Check autodoc generation
      run: |
          eval `luarocks path`
          scripts/autodoc

    - name: Check Admin API definition generation
      run: |
          eval `luarocks path`
          scripts/gen-admin-api-def.sh

    - name: Lint Lua code
      run: |
          eval `luarocks path`
          make lint

    - name: Validate rockspec file
      run: |
          eval `luarocks path`
          scripts/validate-rockspec

    - name: Unit tests
      run: |
          eval `luarocks path`
          make dev
          bin/busted -v -o htest spec/01-unit

