name: Buildifier

on:
  pull_request:
    paths:
    - '**/*.bzl'
    - '**/*.bazel'
    - 'BUILD*'
    - 'WORKSPACE*'
  push:
    paths:
    - '**/*.bzl'
    - '**/*.bazel'
    - 'BUILD*'
    - 'WORKSPACE*'
    branches:
    - master
    - release/*

jobs:

  autoformat:
    name: Auto-format and Check
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo wget -O /bin/buildifier https://github.com/bazelbuild/buildtools/releases/download/5.1.0/buildifier-linux-amd64
          sudo chmod +x /bin/buildifier

      - name: Run buildifier
        run: |
          buildifier -mode=fix $(find . -name 'BUILD*' -o -name 'WORKSPACE*' -o -name '*.bzl' -o -name '*.bazel' -type f)

      # reviewdog/action-setup@v1
      - uses: reviewdog/action-setup@a2416d57a2d4af8546c07bd56c561ec91481c7aa

      - name: Verify buildifier
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GHA_COMMENT_TOKEN }}
        run: |
          TMPFILE=$(mktemp)
          git diff > "${TMPFILE}"
          reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review -name=buildifier < "${TMPFILE}"
