name: Build & Test
on:
  pull_request:
    paths-ignore:
    # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
    - '*.md'
  push:
    paths-ignore:
    # ignore top-level markdown files (CHANGELOG.md, README.md, etc.)
    - '*.md'
    branches:
    - master
    - release/*
    - test-please/*

# cancel previous runs if new commits are pushed to the PR, but run for each commit on master
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-doc-and-unit-tests:
    name: Lint, Doc and Unit tests
    runs-on: ubuntu-20.04

    env:
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: kong

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: kong
          POSTGRES_DB: kong
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 8

    steps:
    - name: Checkout Kong source code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}

    - name: Set path variables
      run: |
        echo "/usr/local/openresty/bin/" >> $GITHUB_PATH
        echo "/usr/local/openresty/nginx/sbin/" >> $GITHUB_PATH
        grep -v '^#' .requirements >> $GITHUB_ENV

    - name: Install packages
      run: sudo apt update && sudo apt install libyaml-dev valgrind libprotobuf-dev libpam-dev

    - name: Install the Kong runtime
      run: |
        curl --fail -sSLo /tmp/kong-runtime.tar.gz https://github.com/Kong/kong-runtime/releases/download/${{ env.KONG_RUNTIME }}/x86_64-linux-gnu.tar.gz
        mkdir /tmp/build
        tar -C /tmp/build -xzf /tmp/kong-runtime.tar.gz
        chmod -R 777  /tmp/build/
        sudo cp -p -r /tmp/build/* /

    - name: Install Kong dev
      run: make dev

    - name: Check autodoc generation
      run: |
          eval `luarocks path`
          scripts/autodoc

    - name: Check Admin API definition generation
      run: |
          eval `luarocks path`
          scripts/gen-admin-api-def.sh

    - name: Lint Lua code
      run: |
          eval `luarocks path`
          make lint

    - name: Validate rockspec file
      run: |
          eval `luarocks path`
          scripts/validate-rockspec

    - name: Unit tests
      run: |
          eval `luarocks path`
          bin/busted -v -o htest spec/01-unit

  integration-tests-postgres:
    name: Postgres ${{ matrix.suite }} - ${{ matrix.split }} tests
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        suite: [integration, plugins]
        split: [first (01-04), second (>= 05)]

    env:
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: kong
      KONG_TEST_DATABASE: postgres
      KONG_SPEC_TEST_GRPCBIN_PORT: "15002"
      KONG_SPEC_TEST_GRPCBIN_SSL_PORT: "15003"
      KONG_SPEC_TEST_OTELCOL_FILE_EXPORTER_PATH: ${{ github.workspace }}/tmp/otel/file_exporter.json
      TEST_SUITE: ${{ matrix.suite }}
      TEST_SPLIT: ${{ matrix.split }}

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: kong
          POSTGRES_DB: kong
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 8

      grpcbin:
        image: kong/grpcbin
        ports:
          - 15002:9000
          - 15003:9001

      redis:
        image: redis
        ports:
          - 6379:6379
          - 6380:6380
        options: >-
          --name kong_redis
      zipkin:
        image: openzipkin/zipkin:2.19
        ports:
          - 9411:9411

    steps:
    - name: Checkout Kong source code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}

    - name: Set path variables
      run: |
        echo "/usr/local/openresty/bin/" >> $GITHUB_PATH
        echo "/usr/local/openresty/nginx/sbin/" >> $GITHUB_PATH
        grep -v '^#' .requirements >> $GITHUB_ENV

    - name: Install packages
      run: sudo apt update && sudo apt install libyaml-dev valgrind libprotobuf-dev libpam-dev

    - name: Install the Kong runtime
      run: |
        curl --fail -sSLo /tmp/kong-runtime.tar.gz https://github.com/Kong/kong-runtime/releases/download/${{ env.KONG_RUNTIME }}/x86_64-linux-gnu.tar.gz
        mkdir /tmp/build
        tar -C /tmp/build -xzf /tmp/kong-runtime.tar.gz
        chmod -R 777  /tmp/build/
        sudo cp -p -r /tmp/build/* /

    - name: Install Kong dev
      run: make dev

    - name: Add gRPC test host names
      run: |
          echo "127.0.0.1 grpcs_1.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 grpcs_2.test" | sudo tee -a /etc/hosts

    - name: Enable SSL for Redis
      if: ${{ matrix.suite == 'plugins' }}
      run: |
          docker cp ${{ github.workspace }} kong_redis:/workspace
          docker cp ${{ github.workspace }}/spec/fixtures/redis/docker-entrypoint.sh kong_redis:/usr/local/bin/docker-entrypoint.sh
          docker restart kong_redis
          docker logs kong_redis

    - name: Run OpenTelemetry Collector
      if: ${{ matrix.suite == 'plugins' }}
      run: |
          mkdir -p ${{ github.workspace }}/tmp/otel
          touch ${{ github.workspace }}/tmp/otel/file_exporter.json
          sudo chmod 777 -R ${{ github.workspace }}/tmp/otel
          docker run -p 4317:4317 -p 4318:4318 -p 55679:55679 \
              -v ${{ github.workspace }}/spec/fixtures/opentelemetry/otelcol.yaml:/etc/otel-collector-config.yaml \
              -v ${{ github.workspace }}/tmp/otel:/etc/otel \
              --name opentelemetry-collector -d \
              otel/opentelemetry-collector-contrib:0.52.0 \
              --config=/etc/otel-collector-config.yaml
          sleep 2
          docker logs opentelemetry-collector

    - name: Tests
      run: |
          eval `luarocks path`
          .ci/run_tests.sh

  integration-tests-dbless:
    name: DB-less integration tests
    runs-on: ubuntu-20.04

    env:
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: kong
      KONG_TEST_DATABASE: 'off'
      KONG_SPEC_TEST_GRPCBIN_PORT: "15002"
      KONG_SPEC_TEST_GRPCBIN_SSL_PORT: "15003"
      KONG_SPEC_TEST_OTELCOL_FILE_EXPORTER_PATH: ${{ github.workspace }}/tmp/otel/file_exporter.json
      TEST_SUITE: dbless

    services:
      grpcbin:
        image: moul/grpcbin
        ports:
          - 15002:9000
          - 15003:9001

    steps:
    - name: Checkout Kong source code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}

    - name: Set path variables
      run: |
        echo "/usr/local/openresty/bin/" >> $GITHUB_PATH
        echo "/usr/local/openresty/nginx/sbin/" >> $GITHUB_PATH
        grep -v '^#' .requirements >> $GITHUB_ENV

    - name: Install packages
      run: sudo apt update && sudo apt install libyaml-dev valgrind libprotobuf-dev libpam-dev

    - name: Install the Kong runtime
      run: |
        curl --fail -sSLo /tmp/kong-runtime.tar.gz https://github.com/Kong/kong-runtime/releases/download/${{ env.KONG_RUNTIME }}/x86_64-linux-gnu.tar.gz
        mkdir /tmp/build
        tar -C /tmp/build -xzf /tmp/kong-runtime.tar.gz
        chmod -R 777  /tmp/build/
        sudo cp -p -r /tmp/build/* /

    - name: Install Kong dev
      run: make dev

    - name: Add gRPC test host names
      run: |
          echo "127.0.0.1 grpcs_1.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 grpcs_2.test" | sudo tee -a /etc/hosts

    - name: Run OpenTelemetry Collector
      run: |
          mkdir -p ${{ github.workspace }}/tmp/otel
          touch ${{ github.workspace }}/tmp/otel/file_exporter.json
          sudo chmod 777 -R ${{ github.workspace }}/tmp/otel
          docker run -p 4317:4317 -p 4318:4318 -p 55679:55679 \
              -v ${{ github.workspace }}/spec/fixtures/opentelemetry/otelcol.yaml:/etc/otel-collector-config.yaml \
              -v ${{ github.workspace }}/tmp/otel:/etc/otel \
              --name opentelemetry-collector -d \
              otel/opentelemetry-collector-contrib:0.52.0 \
              --config=/etc/otel-collector-config.yaml
          sleep 2
          docker logs opentelemetry-collector

    - name: Tests
      run: |
          eval `luarocks path`
          .ci/run_tests.sh

  integration-tests-cassandra:
    name: C* ${{ matrix.cassandra_version }} ${{ matrix.suite }} - ${{ matrix.split }} tests
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        suite: [integration, plugins]
        cassandra_version: [3]
        split: [first (01-04), second (>= 05)]

    env:
      KONG_TEST_DATABASE: cassandra
      KONG_SPEC_TEST_GRPCBIN_PORT: "15002"
      KONG_SPEC_TEST_GRPCBIN_SSL_PORT: "15003"
      KONG_SPEC_TEST_OTELCOL_FILE_EXPORTER_PATH: ${{ github.workspace }}/tmp/otel/file_exporter.json
      TEST_SUITE: ${{ matrix.suite }}
      TEST_SPLIT: ${{ matrix.split }}

    services:
      cassandra:
        image: cassandra:${{ matrix.cassandra_version }}
        ports:
          - 7199:7199
          - 7000:7000
          - 9160:9160
          - 9042:9042
        options: --health-cmd "cqlsh -e 'describe cluster'" --health-interval 5s --health-timeout 5s --health-retries 8

      grpcbin:
        image: moul/grpcbin
        ports:
          - 15002:9000
          - 15003:9001

      redis:
        image: redis
        ports:
          - 6379:6379
          - 6380:6380
        options: >-
          --name kong_redis
      zipkin:
        image: openzipkin/zipkin:2.19
        ports:
          - 9411:9411

    steps:
    - name: Checkout Kong source code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}

    - name: Set path variables
      run: |
        echo "/usr/local/openresty/bin/" >> $GITHUB_PATH
        echo "/usr/local/openresty/nginx/sbin/" >> $GITHUB_PATH
        grep -v '^#' .requirements >> $GITHUB_ENV

    - name: Install packages
      run: sudo apt update && sudo apt install libyaml-dev valgrind libprotobuf-dev libpam-dev

    - name: Install the Kong runtime
      run: |
        curl --fail -sSLo /tmp/kong-runtime.tar.gz https://github.com/Kong/kong-runtime/releases/download/${{ env.KONG_RUNTIME }}/x86_64-linux-gnu.tar.gz
        mkdir /tmp/build
        tar -C /tmp/build -xzf /tmp/kong-runtime.tar.gz
        chmod -R 777  /tmp/build/
        sudo cp -p -r /tmp/build/* /

    - name: Install Kong dev
      run: make dev

    - name: Add gRPC test host names
      run: |
          echo "127.0.0.1 grpcs_1.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 grpcs_2.test" | sudo tee -a /etc/hosts

    - name: Enable SSL for Redis
      if: ${{ matrix.suite == 'plugins' }}
      run: |
          docker cp ${{ github.workspace }} kong_redis:/workspace
          docker cp ${{ github.workspace }}/spec/fixtures/redis/docker-entrypoint.sh kong_redis:/usr/local/bin/docker-entrypoint.sh
          docker restart kong_redis
          docker logs kong_redis

    - name: Run OpenTelemetry Collector
      if: ${{ matrix.suite == 'plugins' }}
      run: |
          mkdir -p ${{ github.workspace }}/tmp/otel
          touch ${{ github.workspace }}/tmp/otel/file_exporter.json
          sudo chmod 777 -R ${{ github.workspace }}/tmp/otel
          docker run -p 4317:4317 -p 4318:4318 -p 55679:55679 \
              -v ${{ github.workspace }}/spec/fixtures/opentelemetry/otelcol.yaml:/etc/otel-collector-config.yaml \
              -v ${{ github.workspace }}/tmp/otel:/etc/otel \
              --name opentelemetry-collector -d \
              otel/opentelemetry-collector-contrib:0.52.0 \
              --config=/etc/otel-collector-config.yaml
          sleep 2
          docker logs opentelemetry-collector

    - name: Tests
      run: |
          eval `luarocks path`
          .ci/run_tests.sh

  pdk-tests:
    name: PDK tests
    runs-on: ubuntu-20.04

    env:
      TEST_SUITE: pdk

    steps:
    - name: Checkout Kong source code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}

    - name: Set path variables
      run: |
        echo "/usr/local/openresty/bin/" >> $GITHUB_PATH
        echo "/usr/local/openresty/nginx/sbin/" >> $GITHUB_PATH
        grep -v '^#' .requirements >> $GITHUB_ENV

    - name: Install packages
      run: sudo apt update && sudo apt install libyaml-dev valgrind libprotobuf-dev libpam-dev

    - name: Install the Kong runtime
      run: |
        curl --fail -sSLo /tmp/kong-runtime.tar.gz https://github.com/Kong/kong-runtime/releases/download/${{ env.KONG_RUNTIME }}/x86_64-linux-gnu.tar.gz
        mkdir /tmp/build
        tar -C /tmp/build -xzf /tmp/kong-runtime.tar.gz
        chmod -R 777  /tmp/build/
        sudo cp -p -r /tmp/build/* /

    - name: Install Kong dev
      run: make dev

    - name: Install Test::Nginx
      run: |
          CPAN_DOWNLOAD=/tmp/cpanm
          mkdir -p /tmp
          curl -o /tmp/cpanm https://cpanmin.us
          chmod +x /tmp/cpanm
          echo "Installing CPAN dependencies..."
          cpanm --notest --local-lib=$HOME/perl5 local::lib && eval $(perl -I $HOME/perl5/lib/perl5/ -Mlocal::lib)
          cpanm --notest Test::Nginx

    - name: Tests
      run: |
          eval `luarocks path`
          eval $(perl -I $HOME/perl5/lib/perl5/ -Mlocal::lib)
          .ci/run_tests.sh