name: Check PR

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      # amannn/action-semantic-pull-request@v5
      - uses: amannn/action-semantic-pull-request@0b14f54ac155d88e12522156e52cb6e397745cfd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
